development:
  adapter: postgresql
  encoding: unicode
  database: multitenant_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: multitenant_test
  pool: 5
  username: postgres
  password: postgres
